export { default as Root } from "./Table.vue";
export { default as Body } from "./TableBody.vue";
export { default as Cell } from "./TableCell.vue";
export { default as Head } from "./TableHead.vue";
export { default as Header } from "./TableHeader.vue";
export { default as Row } from "./TableRow.vue";
export { default as Caption } from "./TableCaption.vue";
export { default as Empty } from "./TableEmpty.vue";
export { default as Footer } from "./TableFooter.vue";
